apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    chart: jellyfin
    targetRevision: "*"
    helm:
      values: |
        service:
          type: LoadBalancer
        persistence:
          config:
            enabled: true
            size: 5Gi
          media:
            enabled: true
            existingClaim: jellyfin-media-pvc
        env:
          TZ: "Europe/Brussels"
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
