service:
  type: LoadBalancer

persistence:
  config:
    enabled: true
    size: 5Gi
  media:
    enabled: false

extraVolumes:
  - name: nfs-media
    persistentVolumeClaim:
      claimName: jellyfin-media-pvc

extraVolumeMounts:
  - name: nfs-media
    mountPath: /media

env:
  TZ: "Europe/Brussels"
