apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-8gears.github.io/n8n-helm-chart
    chart: n8n
    targetRevision: "*"
    helm:
      values: |
        service:
          type: LoadBalancer
          annotations:
            metallb.io/loadBalancerIPs: "192.168.1.155"
        persistence:
          enabled: true
          size: 5Gi
        generic:
          timezone: "Europe/Brussels"
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
