apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: https://n8n2.webbaas.be
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: "*"
    helm:
      values: |
        service:
          type: LoadBalancer
          annotations:
            metallb.io/loadBalancerIPs: "192.168.1.155"
            link.argocd.argoproj.io/external-link: https://n8n2.webbaas.be
        persistence:
          enabled: true
          size: 5Gi
        generic:
          timezone: "Europe/Brussels"
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
