apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verfwinkel-vranken
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: https://verfwinkel-vranken2.webbaas.be
spec:
  project: default
  source:
    repoURL: https://github.com/kcydnavnaad/k3s-homelab.git
    targetRevision: main
    path: apps/verfwinkel-vranken
  destination:
    server: https://kubernetes.default.svc
    namespace: verfwinkel-vranken
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
